### ISSUE TITLE
Request: audio delay / lag option

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc#60]
Hello,
I want to use my TV speakers and my external speakers at the same time but LCD TVs have a delay processing the audio, so the audio output from the TV speakers is delayed compared to the OSSC audio output, so when I use both I get a horrible echoey sound. I think the OSSC should have an audio delay option in the audio options, to adjust the sound lag by -/+ 1/10 millisecond. Which would fix this problem for users who want sound from both at the same time. Thank you

**Comment by marqs85** [comment]
The audio goes directly from ADC to TX, so there is no way to add delay on it - usually modern audio receivers have an option to control that, though. In general simultaneous usage of multiple different amps is not a good idea since you may end up attenuating low frequencies unless you are able to align the delays very closely.
