### ISSUE TITLE
support for hdmi 2.1?

### ISSUE THREAD

**Issue by tails101** [marqs85/ossc#74]
hello i have a question,
will it support hdmi 2.1?
this could fix weird refresh rate issue since hdmi 2.1 support variable refresh rate ( vrr )
and low latency mode for gaming.

**Comment by marqs85** [comment]
The method VRR/QFP works is that a frame is sent to a display at its maximum supported clock (refresh rate) and at the end of each frame there is a variable "wait time" until next frame is ready to be sent. While this makes sense for modern PC or console sources, it's not really useful with classic consoles that scan out a fixed rate which just meets their refresh cycle. If a scaler wanted to introduce a VRR mode for these signals, it'd need to buffer the incoming data in order to be able to send it at a faster rate to display which would counterproductively introduce some latency. Fortunately, many of the displays supporting VRR also support a wider range of refresh rates in a standard mode as well.
